#!/bin/bash

export PATH="$HOME/.pyenv/bin:$PATH:/usr/local/texlive/2022/bin/x86_64-linux:$HOME/.local/bin:$HOME/.emacs.d/bin"
# export WINIT_UNIX_BACKEND=x11
# export KITTY_ENABLE_WAYLAND=1

. "/home/euler/.cargo/env"
